apiVersion: apps/v1
kind: Deployment
metadata:
  name: Order-Management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Order-Management
  template:
    metadata:
      labels:
        app: Order-Management
    spec:
      containers:
      - name: Order-Management
        image: backend-Order-Management:latest
        ports:
        - containerPort: 8006
---
apiVersion: v1
kind: Service
metadata:
  name: Order-Management
spec:
  selector:
    app: Order-Management
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8006
